language: c
sudo: false

addons:
  apt:
    packages:
    - libgmp-dev

before_install:
- mkdir -p ~/.local/bin
- export PATH=~/.local/bin:$PATH
- travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v1.2.0/stack-1.2.0-linux-x86_64-static.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- chmod a+x ~/.local/bin/stack

install:
- stack --no-terminal setup

script:
- stack --no-terminal build

cache:
  directories:
  - $HOME/.stack
