resolver: lts-6.30
packages:
- packdeps-cli
- packdeps-yesod
image:
  container:
    name: snoyberg/packdeps
    base: fpco/stack-run:lts-6.30
    add:
      config: /app/config
      static: /app/static
