resolver: nightly-2018-04-16
packages:
- packdeps-cli
- packdeps-yesod
image:
  container:
    name: snoyberg/packdeps
    base: fpco/stack-run:lts-6.30
    add:
      packdeps-yesod/config: /app/config
      packdeps-yesod/static: /app/static
