resolver: lts-6.30
packages:
- packdeps-cli
- packdeps-yesod
extra-deps:
- optparse-applicative-0.14.0.0
- Cabal-2.0.0.2
image:
  container:
    name: snoyberg/packdeps
    base: fpco/stack-run:lts-6.30
    add:
      packdeps-yesod/config: /app/config
      packdeps-yesod/static: /app/static
