apiVersion: v1
kind: ReplicationController
metadata:
    name: packdeps
    labels:
        name: packdeps
spec:
  replicas: 1
  selector:
    name: packdeps
  template:
    metadata:
        labels:
            name: packdeps
    spec:
        containers:
        - name: packdeps
          image: snoyberg/packdeps
          imagePullPolicy: Always
          command: ["packdeps", "production"]
          workingDir: /app
          ports:
          - containerPort: 3010
            hostPort: 3010
          env:
          - name: PORT
            value: "3010"
          livenessProbe:
              httpGet:
                  path: /
                  port: 3010
