apiVersion: v1
kind: Service
metadata:
    name: packdeps
    labels:
        name: packdeps
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 3010
      protocol: TCP
    selector:
        name: packdeps
